//Web3Reducer
const LOAD_WEB3 = 'LOAD_WEB3';
const WEB3_LOAD_ERROR = 'WEB3_LOAD_ERROR';
const GET_NETWORK = 'GET_NETWORK';
const GET_TOKEN = 'GET_TOKEN';
const GET_EXCHANGE = 'GET_EXCHANGE';

//userReducer
const GET_ACCOUNT = 'GET_ACCOUNT';
const GET_ETH = 'GET_ETH';
const GET_TOKENS = 'GET_TOKENS';
const GET_ETH_CONTRACT = 'GET_ETH_CONTRACT';
const GET_TOKENS_CONTRACT = 'GET_TOKENS_CONTRACT';

//eventReducer
