//Web3Reducer
export const WEB3_LOAD = 'WEB3_LOAD';
export const GET_NETWORK = 'GET_NETWORK';
export const IS_METAMASK_UNLOCKED = 'IS_METAMASK_UNLOCKED';
export const INSTANTIATE_CONTRACTS = 'INSTANTIATE_CONTRACTS';
export const CONTEXT_LOAD_ERROR = 'CONTEXT_LOAD_ERROR';

//userReducer
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_ETH = 'GET_ETH';
export const GET_TOKENS = 'GET_TOKENS';
export const GET_ETH_CONTRACT = 'GET_ETH_CONTRACT';
export const GET_TOKENS_CONTRACT = 'GET_TOKENS_CONTRACT';
export const USER_ERROR = 'USER_ERROR';

//tokenReducer
export const GET_TRADEABLE_TOKENS = 'GET_TRADEABLE_TOKENS';
export const SET_TOKEN = 'SET_TOKEN';
export const TOKEN_ERROR = 'TOKEN_ERROR';

//eventReducer
export const INIT_DEPOSIT_EMITTER = 'INIT_DEPOSIT_EMITTER';
export const INIT_WITHDRAW_EMITTER = 'INIT_WITHDRAW_EMITTER';
export const ADD_DEPOSIT_EVENT = 'ADD_DEPOSIT_EVENT';
export const ADD_WITHDRAW_EVENT = 'ADD_WITHDRAW_EVENT';
export const REMOVE_DEPOSIT_EVENT = 'REMOVE_DEPOSIT_EVENT';
export const REMOVE_WITHDRAW_EVENT = 'REMOVE_WITHDRAW_EVENT';
export const LOAD_PAST_ORDERS = 'LOAD_PAST_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const LOAD_PAST_DEPOSITS = 'LOAD_PAST_DEPOSITS';
export const LOAD_PAST_WITHDRAWS = 'LOAD_PAST_WITHDRAWS';
export const GET_EXPIRATION = 'GET_EXPIRATION';
export const EVENT_ERROR = 'EVENT_ERROR';
